[package]
name = "simple-wallpaper-gui"
version = "0.1.0"
edition = "2024"

[lib]
path = "mod.rs"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }
simple-wallpaper-core = { path = "../core" }
tokio = { version = "1.41.1", features = ["rt", "sync", "io-util", "time"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }