[package]
name = "simple-wallpaper"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "swp"
path = "src/main.rs"

[dependencies]
clap     = { version = "4.5.53", features = ["derive"] }
colored  = "3.1.1"
inquire  = "0.9.4"
iced     = { version = "0.13.1", features = ["image"] }
image    = "0.25.8"
rand     = "0.10.0"
thiserror = "2.0.12"
walkdir  = "2.5.0"
