[package]
name = "simple-wallpaper"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "src/cli", "src/core"]
resolver = "2"

[[bin]]
name = "swp"
path = "src/main.rs"

[dependencies]
clap     = { version = "4.5.53", features = ["derive"] }
colored  = "3.1.1"
simple-wallpaper-cli = { path = "src/cli" }
simple-wallpaper-core = { path = "src/core" }
