[package]
name = "simple-wallpaper-cli"
version = "0.1.0"
edition = "2024"

[lib]
path = "mod.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.1.1"
inquire = "0.9.4"
simple-wallpaper-core = { path = "../core" }
uuid = { version = "1.18.1", features = ["v4", "serde"] }